### ISSUE TITLE
Require a feature that change browser based on battery status

### ISSUE THREAD

**Issue by doskey** [nthloop/Objektiv#22]
If the mac is in-charge status, I would like to change the default browser to chrome because it is fast. But, if the mac is using battery, I would like to change the safari as default browser. Chrome drain the battery fast as its speed.

**Comment by cmeury** [comment]
@doskey Thanks for bringing this issue here. It's an interesting use case, but somewhat niche. I am not sure if this should really be in scope for such a dedicated, small tool. As a counter-proposal, what do you think about adding AppleScript support to the tool, so any kind of these small automations could be added? (Also, as a disclaimer, I'm not code contributor around here, just maintaining the things around it.)
